### ISSUE TITLE
Convert Rackspace account to individual accounts

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#1072]
See https://github.com/nodejs/build/pull/995#discussion_r159559277

### TODO

- [ ] Have everyone in nodejs_build_infra create individual accounts and connect them to the shared account
  - [x] rvagg
  - [x] joaocgreis
  - [ ] jbergstroem
  - [x] mhdawson
  - [x] gibfahn
- [ ] ??? Close or stop using the existing shared account once the individual accounts are set up
- [ ] Update [`doc/access.md`](https://github.com/nodejs/build/tree/master/doc/access.md) to note the change to individual accounts.

@rvagg I assume you're going to need to take this one, I'm not sure how this should work.

**Comment by rvagg** [comment]
@gibfahn @jbergstroem @mhdawson @joaocgreis can each of you please log in with the primary creds for our Rackspace account and visit https://account.rackspace.com/users and add yourself as a user. Obviously you don't need to share details in the admin_logins.md doc but you should make it so you can log in under your own account. We can then manage this account per-user and we should be able to track activity by user as well.

**Comment by gibfahn** [comment]
@rvagg what am I doing wrong?

![image](https://user-images.githubusercontent.com/15943089/34669978-33fa9f92-f46c-11e7-824e-ebbed215eab6.png)

<img width="441" alt="image" src="https://user-images.githubusercontent.com/15943089/34669986-3cbd0af2-f46c-11e7-8a02-b13e5f88fb23.png">

**Comment by rvagg** [comment]
Uhhhhhhhh no idea! I made an account from scratch for this. Maybe you have to "create user" and go through it to make a distinct one for this purpose.

**Comment by joaocgreis** [comment]
I used the "Create User" button and it worked well. Apparently, the objective is not to create a Rackspace Cloud account and then add it here, but instead to create a dedicated user under our account. I see another account prefixed with `node.`, so perhaps it's common for people who already have Rackspace accounts to create dedicated users with different names.

**Comment by gibfahn** [comment]
@mhdawson @jbergstroem ping regarding creating accounts.

**Comment by mhdawson** [comment]
Created my account using "Create User" butto.
