### ISSUE TITLE
Converged release work plan

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#135]
* [ ] Connect nodejs.org to new Jenkins and formulate converged release procedure
* [ ] Ensure test CI covers the converged repo/branches
* [ ] Signing builds with foundation keys
* [ ] Release candidates for converged repo
* [ ] Finish and upstream node-gyp changes

**Comment by orangemocha** [comment]
I am working on the second item: "Ensure test CI covers the converged repo/branches".
