### ISSUE TITLE
Short-term CI infra plans (discussion)

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#19]
The current state of the build infrastructure can be seen here: http://jenkins.node-forward.nodesource.com/

Summary:
 - We have automatic builds for both io.js and libuv
 - "multi" builds target the initial cluster we have been building:
   - Ubuntu 10.04, 12.04, 14.04 (and 14.04 32-bit)
   - CentOS 6, CentOS 7 (RHEL 6 & 7 by proxy)
   - Windows Server 2012 with Visual Studio 2013
   - Ubuntu 14.04-based ARMv7
 - "containers" is a cluster of the 3 LTS Ubuntu version run in Docker containers, see [build-containers](https://github.com/iojs/build-containers) for how they work, these are intended to be run against all new incoming pull requests from untrusted sources (mostly everyone except TC)

Currently we also have the ability to trigger builds on either the full "multi" or "containers" from any repo on GitHub but they must be triggered manually by someone who has access to Jenkins. So far that's only myself, @ryanstevens and @indutny but I can expand that list to the full TC and other trusted helpers.

**Short-term goals**

- [ ] Hook up to the GitHub status API so we can run "containers" builds for every PR and report the status back to the repo inline
- [ ] Hook up "multi" builds for a "trusted" list, initially comprised of the TC
- [ ] Make it easier for TC (et. al.) to request arbitrary pull requests be run against "multi" prior to merge (I'm actually thinking that a bot putting a message in a PR with a link that works for TC members would be good enough here for now).

**Pre-first-release goals**

- [ ] Fill out the missing parts of the CI cluster, see #18 
- [ ] Start collecting build artifacts and storing in S3 to make releases easier *(I think this is the best approach for releases right now)*

**Mid-term goals**

- [ ] Expand the CI cluster to include some more meaningful platforms, particularly those that the libuv team want because they have broader cross-platform goals than io.js and are heavily relied upon by many other projects. See the README of this repo, #14 and #17 for further info and discussion on platforms.
- [x] Find Windows people who care and can help make Windows better! #15 

**Miscellaneous goals**

- [ ] Bootstrap a performance-focused team by setting up a basic platform for a nightly (or other regular) run of a performance suite (to be developed) so report back gut-feel numbers at a minimum, [arewefastyet](http://arewefastyet.com/)-style. I don't see this as a long term responsibility of the build team and it should be a separate team focused on performance and obsessed with _how_ best to measure and report performance over time; we just need to bootstrap it because we're the infra team and the hardware and tooling connects logically with what we're doing. I'm proposing @brycebaril as initial lead for this team. Needs further discussion from TC but I know they _need_ something better than the ad-hoc micro-benchmarking efforts that go on now.

Beyond that, we want to fully make our own CI tooling and deprecate Jenkins, but that's a lower priority than just moving io.js forward.

**Comment by bnoordhuis** [comment]
@rvagg Are there still actionable items left?

**Comment by rvagg** [comment]
yeah, plenty of actionable items that are not properly documented elsewhere, should probably leave this open for now

**Comment by jbergstroem** [comment]
Almost a year! I think we've covered most things on this list, with a gap in containers/auto-testing. At the same time I think our strategy in that department has changed. Inclined to close.
