### ISSUE TITLE
low disk space in Macos machines

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3450]
There are some machines with low space in Test Jenkins

cc: @joyeecheung @aduh95. [Slack context](https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1691759958570799)

**Machines affected**
- [x] https://github.com/nodejs/jenkins-alerts/issues/394
- [x] https://github.com/nodejs/jenkins-alerts/issues/395
- [x] https://github.com/nodejs/jenkins-alerts/issues/396
- [x] https://github.com/nodejs/jenkins-alerts/issues/397

**Action plan**
- [x] SSH to the machines and execute the cleaner #3089

**Comment by UlisesGascon** [comment]
**Current status**

Three machines recovered, only `test-nearform-macos10.15-x64-2` is being challenging. I will check disk usage in details to see where is the issue

**Comment by UlisesGascon** [comment]
**Current status**

All the machines restored, so I will close this issue.


Not sure why `test-nearform-macos10.15-x64-2` needed an additional reboot to apply the changes, the usage was fine 🤔 

```
df -h
Filesystem      Size   Used  Avail Capacity iused     ifree %iused  Mounted on
/dev/disk1s5    51Gi   10Gi   19Gi    36%  488456 536620904    0%   /
devfs          186Ki  186Ki    0Bi   100%     642         0  100%   /dev
/dev/disk1s1    51Gi   21Gi   19Gi    52% 1482934 535626426    0%   /System/Volumes/Data
/dev/disk1s4    51Gi  1.0Mi   19Gi     1%       1 537109359    0%   /private/var/vm
map auto_home    0Bi    0Bi    0Bi   100%       0         0  100%   /System/Volumes/Data/home
```
