### ISSUE TITLE
Infrastructure for Orka (2024 and beyond)

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3686]
I plan to work on it during the weekend, so I can provide a good overview on the next build meeting on Tuesday.

**Current status**

- [x] Cleaned up all the macos machines that are available via SSH
- [ ] Open discussion with support for macstadium machines with ssh problems: https://github.com/nodejs/build/issues/3667 and https://github.com/nodejs/build/issues/3685
- [x] Open discussion to apply upgrade in the Firewall: https://github.com/nodejs/build/issues/3642 
- [ ] Review Orka state
- [ ] Plan the final allocation for resources in Orka
- [ ] Provide access for @ryanaslett to the resources: https://github.com/nodejs/build/issues/3658
- [ ] Prepare and deliver and onboarding session for @ryanaslett to the Orka infrastructure

**Comment by UlisesGascon** [comment]
### Next Orka state

_updated on April 19, 2024_

**Intel Nodes**

| SSH port | Node: macpro-4 | Node: macpro-5 | Node: macpro-6 |
|----------|----------|-------------|------|
| 8822 | release-macos11-x64-1  | **test-macos13-x64-2** | test-macos11-x64-1 |
| 8823 | **test-macos13-x64-1**  | **release-macos13-x64-1** | test-macos11-x64-2 |
| 8824 | **release-macos13-x64-2** | test-macos1015-x64-2 | test-macos1015-x64-1 |
| 8825 | _empty_  | _empty_ | _empty_ |

**ARM Nodes**

_We assume that ARM Nodes can handle only 2 VMs and not +4 as Intel in the past due license limitations. This needs to be confirmed with support AFAIK?_

| SSH port | Node: arm-1 | Node: arm-2 |  Node: arm-3 | Node: arm-4 | Node: arm-5 |
|----------|-------------|-------------|-------------|-------------|-------------|
| 8822 | **test-nearform-macos11.0-arm64-1** | **release-macstadium-macos11.0-arm64-1** | **test-macstadium-macos11.0-arm64-4** | **test-macos13-arm64-2** | **release-macos13-arm64-2** |
| 8823 | **release-nearform-macos11.0-arm64-1** | **release-macos13-arm64-1** | **test-macstadium-macos11.0-arm64-3** | **test-macos13-arm64-1** | _empty_ |

**Comment by targos** [comment]
> 	release-macos13-x64-2

I don't think it's necessary to have two identical release machines.

**Comment by targos** [comment]
> test-nearform-macos11.0-arm64-1

Are these typos?

**Comment by UlisesGascon** [comment]
Great feedback @targos! I updated the tables

**Comment by targos** [comment]
> > release-macos13-x64-2
> > release-macos13-arm64-2
> 
> I don't think it's necessary to have two identical release machines.

Actually, I think we should have one x64 and two arm64 machines, because there are two jobs that run on macos-arm64 during a release (osx11-release-pkg and osx11-arm64-release-tar).

**Comment by ryanaslett** [comment]
Some questions/thoughts/suggestions:

1. Requirements Question: Do we still need to support 10.15 and/or 11? from (https://github.com/nodejs/node/blob/main/BUILDING.md#supported-platforms) I see:

> Node.js does not support a platform version if a vendor has expired support for it. In other words, Node.js does not support running on End-of-Life (EoL) platforms. This is true regardless of entries in the table below.

And the table lists `MacOS 11>`.

And that table may be outdated as it seems as though MacOS 11 was EOL as of November 2023 ?

2. ARM support in Orka: 

> We assume that ARM Nodes can handle only 2 VMs and not +4 as Intel in the past due license limitations. This needs to be confirmed with support AFAIK?

https://orkadocs.macstadium.com/docs/apple-arm-based-support confirms this:

> IMPORTANT
> 
> You can deploy up to 2 VMs per Apple silicon-based node.


3. From what I can gather macOS infra seems to be brittle, with nodes often running into disk issues/maintenance issues.

https://github.com/nodejs/build/issues/3592
https://github.com/nodejs/build/issues/3685
(https://github.com/nodejs/build/issues?q=is%3Aissue+macos+is%3Aclosed+disk) etc.

My suggestion to avoid Jenkins worker decay is to lean into an ephemeral node strategy so that each build has a fresh Orka instance to run on.

We can do that with the following Jenkins plugin for Orka:
https://plugins.jenkins.io/macstadium-orka/#plugin-content-ephemeral-agents

We would first need to set up a packer build process to create our VM images so that Orka would have a baseline image to create:
https://orkadocs.macstadium.com/docs/packer

The packer process can leverage our existing ansible playbooks:
https://developer.hashicorp.com/packer/integrations/hashicorp/ansible/latest/components/provisioner/ansible.

This strategy would require that we have an Orka3.0 cluster. Rather than trying to do an upgrade of the existing cluster, I propose that we ask macstadium to allow us to provision a new cluster with the resources we need in it (enough arm/intel backing nodes for our macos11/13 testing and release),  get it built/provisioned and working, and then decommission/return all the existing macstadium/orka machines.

I believe this would end up with us using roughly the same amount of resources, so should be palatable for macstadium to support this transition.

**Comment by mhdawson** [comment]
> This strategy would require that we have an Orka3.0 cluster. Rather than trying to do an upgrade of the existing cluster, I propose that we ask macstadium to allow us to provision a new cluster with the resources we need in it (enough arm/intel backing nodes for our macos11/13 testing and release), get it built/provisioned and working, and then decommission/return all the existing macstadium/orka machines.

+1 from me if Macstadium will support that

**Comment by UlisesGascon** [comment]
Quick update from our last call with MacStadium:

Next week we will have a new Orka cluster (v3) that includes 2 nodes (Intel and ARM):
- `Mac Studio - G1MC M1M/10/32/16/64GB/2TB/10G`
- `Mac mini G4E - i7/3.2Ghz/6C/64G/1T/SSD/10G`


**Goals:**
- [ ] Setup Ephimeral nodes from Jenkins on demand
- [ ] Define VMs for each MacOS Version/arch and use (Test or release) using [packer](https://developer.hashicorp.com/packer) 
- [ ] Move the current jobs to the new cluster
- [ ] Decommission the Bare metal machines and existing Orka Cluster (and Inter Nodes)
- [ ] Support Marketing activities related (@UlisesGascon will provide more details)
 
**Deadline**
The idea is to try to achieve this transition in 30 days.

**Comment by UlisesGascon** [comment]
Based on the support ticket [SERVICE-188003](https://portal.macstadium.com/support-center/tickets/SERVICE-188003) and the documentation https://orkadocs.macstadium.com/docs/compatibility-versions#macos-and-apple-hardware. 
![Screenshot from 2024-08-27 19-49-39](https://github.com/user-attachments/assets/0c85b0d0-8ee2-4289-bdb1-be243368b5b6)



We might won't be able to migrate MacOS ARM VMs to Orka due lack of support, so we might need to keep the Bare Metal machines.

This needs to be confirmed (cc: @ryanaslett )

**Comment by UlisesGascon** [comment]
**Current status**

I will be on PTO from the 19th to the 25th. I made some changes to the templates to add the missing dependencies (https://github.com/nodejs/build/pull/3906).

So, @ryanaslett, in case you want to help with this during my time off:
- [ ] Check why the `iojs+release-Ulises-test-orca` is not passing. The current error (`10:09:52 Makefile:1030: *** No xz command, cannot continue.  Stop.`) ([details](https://ci-release.nodejs.org/job/iojs+release-Ulises-test-orca/nodes=osx13-arm64-release-tar/lastBuild/console)) is related to the `PATH` (I think), as `xz` is included on all the machines already since my last PR.
- [ ] Try to modify the base image for release and test machines to include and use `Xcode 15.2`, based on [the discussion](https://openjs-foundation.slack.com/archives/C07JD5SSRUK/p1726216871577909) with @targos.
- [ ] Keep running and patching the other pipelines that we cloned with @mhdawson.

Probably the next errors in the CI will be related to the users; currently, we only have the admin user. Maybe we need to create a separate one like `iojs` in order to make the CI pipelines work.

**Comment by ryanaslett** [comment]
> Check why the iojs+release-Ulises-test-orca is not passing. The current error (10:09:52 Makefile:1030: *** No xz command, cannot continue.  Stop.) ([details](https://ci-release.nodejs.org/job/iojs+release-Ulises-test-orca/nodes=osx13-arm64-release-tar/lastBuild/console)) is related to the PATH (I think), as xz is included on all the machines already since my last PR.

Started in on this. 

The PATH variable is set on the existing macos machines via the script that launches the jenkins agent:
This template: 
https://github.com/nodejs/build/blob/main/ansible/roles/jenkins-worker/templates/start.j2#L10
Creates a script here: 
https://github.com/nodejs/build/blob/main/ansible/roles/jenkins-worker/tasks/main.yml#L179-L185
And this Template:
https://github.com/nodejs/build/blob/main/ansible/roles/jenkins-worker/templates/org.nodejs.osx.jenkins.plist
Gets put into /Library/LaunchDaemons
https://github.com/nodejs/build/blob/main/ansible/roles/jenkins-worker/vars/main.yml#L33-L37

I've added ARCH, DESTCPU, and PATH to the Environment variables to the Orka Cluster Cloud Template configurations on ci-release machine.  

The osx13-x64-release-tar job worked and signed the tarball, but failed to push the release to node-www, so, need to adjust that next.

![image](https://github.com/user-attachments/assets/8396c7dc-ca79-449a-ae25-ba2b86b4ebb7)

**Comment by targos** [comment]
We need this config in the image:
https://github.com/nodejs/build/blob/main/ansible/roles/release-builder/files/ssh_config

**Comment by richardlau** [comment]
> We need this config in the image: https://github.com/nodejs/build/blob/main/ansible/roles/release-builder/files/ssh_config

node-www also has a ufw2 firewall and will not allow connections from ip addresses not on the allowlist.

**Comment by ryanaslett** [comment]
I've added the main orka address to the ufw2 firewall on node-www (199.7.167.98) I've confirmed that this is the address that ephemeral nodes will all appear as to node-www.

**Comment by ryanaslett** [comment]
I've requested the new nodes from MacStadium to fill out the rest of our capacity, and got a response today that they are aiming to have the nodes installed by Wed, Oct 30th.

**Comment by targos** [comment]
It's been a month now. Did we get the new nodes?

**Comment by targos** [comment]
I'm sorry to insist, but I don't know what else to do to move this forward :(

**Comment by mhdawson** [comment]
@ryanaslett, @UlisesGascon any update on this?

**Comment by ryanaslett** [comment]
Hi, yes, we did get the nodes, but havent fully transitioned testing over to using them as there was still an open question about whether or not we had the right xcode and OS versions. 

Apologies that I didnt see your question earlier.

I've been wrapping up some other OpenJS project stuff for the end of the year, but I can refocus on this once more to make sure its in a stable situation.

**Comment by anonrig** [comment]
Existing macOS machines (due to outdated clang/gcc versions) are blocking 4 pull-requests:
- https://github.com/nodejs/node/pull/56218
- https://github.com/nodejs/node/pull/56080
- https://github.com/nodejs/node/pull/56063
- https://github.com/nodejs/node/pull/54990

Should we start talking about lowering the support tier of macOS? The oldest PRs are from September 17 (almost 3 months ago).

**Comment by targos** [comment]
Some interesting news, coming from https://github.com/nodejs/node-v8/issues/295 and a Slack chat with @joyeecheung:

- V8 is currently built with Xcode 15.1, with a compatibility target of macOS 11.0 (source: https://source.chromium.org/chromium/chromium/src/+/main:build/config/mac/mac_sdk.gni)
- We have the same compatibility target
- In the release CI, we have two different Xcode versions (source: https://ci-release.nodejs.org/job/iojs+release/10687)
  - `osx13-x64-release-tar` uses version 16.0 (`clang-1600.0.26.3`). Builds of Node.js with latest V8 are successful with it.
  - `osx13-arm64-release-tar` uses version 14.3 (`clang-1403.0.22.14.1`). Builds of Node.js with latest V8 fail with it.

That said, I suggest:
- We bump the [official minimum version required to build Node.js](https://github.com/nodejs/node/blob/main/BUILDING.md#supported-toolchains) to at least Xcode 15.1 (we could decide on a later version too).
- We make sure the decided version is the one used in the CI jobs (release and test, x64 and arm64)

**Comment by targos** [comment]
Note that officially (according to https://developer.apple.com/download/applications/), Xcode 16.1 requires at least macOS 14.5 to run, and according to Wikipedia, Xcode 16.0 did too. So I don't know how the `osx13-x64-release-tar` job is able to run, but it may be risky not to upgrade macOS to a supported version.

**Comment by joyeecheung** [comment]
I left my machine that has macOS 13 + Apple Clang 14 now so can't provide more details until after the holidays but FWIW: when I tried to install the latest system update for 13, the only available update was upgrading to Sequoia, and nothing showed up when I tried to look for last compatible update of XCode or command line tools. If somehow it is possible to run macOS 13 with XCode 16 we should likely need to document how to install it, or contributors on macOS 13 may have a hard time getting it to build.

**Comment by targos** [comment]
This is how we manually install Xcode on the build machines: https://github.com/nodejs/build/blob/main/ansible/MANUAL_STEPS.md#full-xcode

**Comment by joyeecheung** [comment]
Also my 2cents: V8 uses tip of tree clang, so that's currently clang 20, and they have been doing a lot of C++ modernization that lower versions of clang aren't very good at parsing. I did quite a few patching to make V8 build on macOS 13 and Clang 14 in https://github.com/joyeecheung/node/tree/fix-macos-13 and many of the fixes don't look very acceptable in the upstream because they basically just revert the modernization. If we are upgrading the build system the least friction route would probably be to just require Sequoia and XCode 16 to build, though we can keep targeting 11.

**Comment by UlisesGascon** [comment]
> If somehow it is possible to run macOS 13 with XCode 16 we should likely need to document how to install it, or contributors on macOS 13 may have a hard time getting it to build (or if it just doesn't work then we need to tell contributors to upgrade to Sequoia)

For the new Orka machines, we are using Packer, and the instructions include some manual steps on how to install it that are replicable for local machines as well:  
https://github.com/nodejs/build/tree/main/orka/templates#manual-steps-for-the-release-images.  

We probably want to update the commands and ensure that we are using the correct version 👍

**Comment by anonrig** [comment]
Is there any update/progress on this issue?

**Comment by UlisesGascon** [comment]
Let me ping @ryanaslett! AFAIK we were testing the new ephemeral instances and waiting for a HW upgrade in the new cluster so we can decommission the old VMs and move all the workloads for both CI environments, but not sure if this was completed or not.

**Comment by anonrig** [comment]
This issue is currently the only blocker for adding URLPattern to Node.js - https://github.com/nodejs/node/pull/56452

**Comment by richardlau** [comment]
Linking this to https://github.com/openjs-foundation/infrastructure/issues/17.

**Comment by ryanaslett** [comment]
Update:

The images that back the test instances on our cluster are in a state where I believe we can unblock our blocked PR's.

>  If somehow it is possible to run macOS 13 with XCode 16 we should likely need to document how to install it, or contributors on macOS 13 may have a hard time getting it to build (or if it just doesn't work then we need to tell contributors to upgrade to Sequoia).

The instances have osx13.0, with XCode 16 installed on them (both on the Arm and Intel images). XCode16 was installed via the command line (despite apple's compatibility matrix) and it appears to be working fine for our purposes. 

- Arm test: https://ci.nodejs.org/job/node-test-commit-osx-arm-Ulises-test-orca/nodes=osx13-arm64/3/console
- Intel test: https://ci.nodejs.org/job/node-test-commit-osx-arm-Ulises-test-orca/nodes=osx13-x64/4/console

I agree that's likely not ideal from a contributor perspective -> to trick a Ventura machine into running Xcode 16, which works fine for compiling, but likely doesnt run at all in the GUI. 

> In the release CI, we have two different Xcode versions

That was an oversight where xcode16 didn't fully get installed on the Arm image before it was deployed.   I have an updated release image that has xcode16 prepared, but am hesitant to deploy change that since today I *also* updated those release images to renew the expired signing certificates, and I wouldn't want to impact the current release schedule any further than it already has been . I can deploy that when the releases have actually happened.

The testing images can be enabled as soon as I get enough consensus that its acceptable to run tests on macos13 with xcode 16.

If we should decide those ought to be sequoia and xcode16, I can make images for those, but that'll likely require more time because we'll likely want all four images (test/release X arm/intel) to be updated.

**Comment by targos** [comment]
I see `osx13-arm64` and `osx13-x64` labels in both [node-test-commit-osx](https://ci.nodejs.org/job/node-test-commit-osx/) [node-test-commit-osx-arm](https://ci.nodejs.org/job/node-test-commit-osx-arm/) jobs.
This seems redundant. Should we remove `node-test-commit-osx-arm` from `node-test-pull-request`?

**Comment by ryanaslett** [comment]
> I see `osx13-arm64` and `osx13-x64` labels in both [node-test-commit-osx](https://ci.nodejs.org/job/node-test-commit-osx/) and [node-test-commit-osx-arm](https://ci.nodejs.org/job/node-test-commit-osx-arm/) jobs. This seems redundant. Should we remove `node-test-commit-osx-arm` from `node-test-pull-request`?

Agreed. I've configured `node-test-commit-osx` to run both `osx13-arm64` and `osx13-x64` labels, and have disabled the `node-test-commit-osx-arm` on `node-test-pull-request`.  We can remove it entirely once all the dust settles.

**Comment by ryanaslett** [comment]
Separate related question to the OSX instances: Should these jobs be using ccache? We have an available shared storage that we can use so that when an ephemeral instance is launched, it can have an existing warmed ccache, but it doesnt look like the osx11/osx10.15 machines were using ccache either, so Im unsure if that's not applicable to builds on osx or not.

**Comment by richardlau** [comment]
They're supposed to be. 

e.g. from today's https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-v18.x-staging/453/
https://ci.nodejs.org/job/node-test-commit-osx/63373/nodes=osx1015/consoleFull
```console
10:01:27 + export CCACHE_BASEDIR=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015
10:01:27 + CCACHE_BASEDIR=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015
10:01:27 + export 'CC=/usr/local/bin/ccache cc'
10:01:27 + CC='/usr/local/bin/ccache cc'
10:01:27 + export 'CXX=/usr/local/bin/ccache c++'
10:01:27 + CXX='/usr/local/bin/ccache c++'
10:01:27 ++ getconf _NPROCESSORS_ONLN
10:01:27 + export JOBS=4
10:01:28 + JOBS=4
10:01:32 + NODE_TEST_DIR=/Users/iojs/node-tmp
10:01:32 + FLAKY_TESTS=dontcare
10:01:32 + make run-ci -j 4
10:01:32 python3 ./configure --verbose 
10:01:32 Node.js configure: Found Python 3.7.7...
10:01:32 Detected clang C++ compiler (CXX=/usr/local/bin/ccache c++) version: 11.0.3
10:01:32 Detected clang C compiler (CC=/usr/local/bin/ccache cc) version: 11.0.3
...
```

Admittedly the build time would suggest that either build times on macOS are much worse than other platforms or the ccache set up  on macOS is broken.

**Comment by ryanaslett** [comment]
> They're supposed to be.

Ah, yes. I see that. They were not using that on the tests I ran, so not sure what's different between the 'real jobs' and my smoke test setup.

I'm looking into why its not respecting the ccache env vars. I think I may need to use a .ccache config instead of env vars. 

Also, we're only getting half the instances for our arm builds as they were set to 6 cpu's and those nodes only had 10 available. I've reset those to 5 but the queue will have to clear out before it shuts down the 6 cpu vm's and re-creates 2 5cpu vms.

**Comment by targos** [comment]
The builds generally look good, but yeah they definitely need ccache. At least for x64, which takes around 3 hours (vs 20 minutes for arm64!)

**Comment by ryanaslett** [comment]
I had set up the x64 machines to use the ccache earlier today, and when I checked the shared cache directory, it had created all of the hash prefix subdirs, so I assumed it was working.

But I just dug deeper with the ccache debug logs and turns out it created those dirs without group perms, but the processes can only write as group members. 

I just did a chmod g+w on the whole cache dir and now all the files are starting to cache.  Hopefully this speeds things up a bit.

There does still seem to be something awry with the x64 machines connecting to the shared drive, as doing simple things like an ls take 22 seconds (wheras on the arm machines it acts like a normal HD)

**Comment by ryanaslett** [comment]
Status update on MacOS testing/Release infra.

Our Orka3 cluster is now fully responsible for the x86/arm jobs and is running images that are macos13 with Xcode16 on them.

The testing images are configured to use a permanent shared storage for ccache such that new ephemeral instances will all see the same warmed cache.

There seems to be an issue with differences in how each architecture accesses this storage: as such, the x86 machines are running builds *very* slowly, averaging about 2 hours for a test, whereas the ARM machines are done in about 15min.

I have an open ticket with Macstadium to investigate this to see if there's another way to establish the mount to that shared storage on the x86 machines that is more performant.

The infrastructure can support four x86 instances, and four arm instances. I have configured the test infra to only use a maximum of 3 so that a burst of PR testing doesnt block releases.  

Next steps:

- [ ] Create a macos 14 image with xcode16 since macos13/xcode16 is an unusual combo only achievable via unusual installation techniques.
- [ ] Document access to the orka infrastructure, and update the documentation with what's been done in general.
- [ ] Decomission the old machines.

**Comment by ryanaslett** [comment]
Thanks @UlisesGascon . I had just done those locally, came here to post and saw these PR's :/ . But, still saved time on review waits.

I also went ahead and removed any osx 'testing' related jobs we had created during this process, as well as converted any ci testing job that was using the osx10.15 or osx11 labels to use the osx13-{arch} labels.
