### ISSUE TITLE
Planning/requirements for Node.js 23

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3807]
Opening this issue to keep track of build/infra requirements for Node.js 23 (due October 2024). I suggest we keep this issue as an index to other issues and try to keep discussion to the linked issues to make it easier to keep track of conversations.

@nodejs/build Feel free to update this list, adding new issues as required (or comment if you are unable to edit).

# macOS 

- [ ] Increase minimum macOS version https://github.com/nodejs/node/issues/53561
- [ ] Infrastructure for Orka https://github.com/nodejs/build/issues/3686

# Linux

- [x] move minimum supported gcc to gcc 12 for Node.js 23 https://github.com/nodejs/build/issues/3806
  - [x] https://github.com/nodejs/build/pull/3846
    - [x] https://github.com/nodejs/build/issues/3855
  - [x] https://github.com/nodejs/build/pull/3845
  - [x] https://github.com/nodejs/build/pull/3844
  - [x] https://github.com/nodejs/build/pull/3865
  - [x] https://github.com/nodejs/build/pull/3886
  - [x] https://github.com/nodejs/build/pull/3889
  - [x] https://github.com/nodejs/build/pull/3890
  - [x] https://github.com/nodejs/node/pull/54967

# Windows

~~- [ ] build node.js using clangcl when under Windows https://github.com/nodejs/node/issues/52809~~
- [x] Should we drop support for 32 bit Windows? https://github.com/nodejs/node/issues/42543 https://github.com/nodejs/node/pull/53184

# AIX

- [x] move minimum supported gcc to gcc 12 for Node.js 23 https://github.com/nodejs/build/issues/3806
  - [x] https://github.com/nodejs/node/pull/53585
  - [x] https://github.com/nodejs/build/pull/3858
  - [x] https://github.com/nodejs/node/pull/54338

**Comment by mhdawson** [comment]
+1 for moving the gcc level to 12
I'll let @StefanStojanovic commenton the Windows one

**Comment by targos** [comment]
Along with https://github.com/nodejs/node/issues/53561, we should also upgrade the minimum Xcode and Clang versions.

Newer V8 versions cannot be compiled by the ones we have in macOS 11.

**Comment by targos** [comment]
We would need at least Xcode 16 for good C++20 support: https://developer.apple.com/xcode/cpp/#c++20, which is annoying as that version hasn't even been released yet!

Given https://endoflife.date/macos and https://github.com/nodejs/node/issues/53561, I suggest we bump the CI versions to macOS 13.

**Comment by mhdawson** [comment]
From discussion in the meeting today, sounds like for 23 we are not ready to move to clang so we won't include in this release.
