### ISSUE TITLE
AIX: Backlog

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#551]
We have a few tasks outstanding in respect to the AIX configuration. @gibfahn was asking if we had a list somewhere so this issue will act as that list:

- [x] install version of python 2.x that supports PIP - https://github.com/nodejs/build/issues/533
- [x] enable jenkins agent auto start - https://github.com/nodejs/build/issues/534
- [x] submit PR to install instructions to cover disk io optimization. - https://github.com/nodejs/build/issues/537
- [x] make binaries needed for AIX install available through scp (or other appropriate method) from 
      jenkins masker
- [ ] update Ansible scripts so that they pull binaries instead of requiring manual install

**Comment by mhdawson** [comment]
@gibfahn as requested.  If there are others I'll add to this list.  The installation of the python version that supports PIP is the most urgent.  Is that something you can look at this week ?   We'll want to look at the dependencies carefully as I ran into problems in previous updates and stage to one machine at a time.

**Comment by gibfahn** [comment]
I'm pretty sure that there's an issue with curl on the AIX boxes, not sure if it's a LIBPATH issue or if something's wrong with the install. We don't have it on IBM machines, so it's definitely fixable, just annoying (it means things have to be scp'd rather than just curl'd.

```bash
$ curl
exec(): 0509-036 Cannot load program curl because of the following errors:
        0509-022 Cannot load module /usr/lib/libcurl.a(libcurl.so.4).
        0509-150   Dependent module /opt/freeware/lib/libcrypto.a(libcrypto.so) could not be loaded.
        0509-152   Member libcrypto.so is not found in archive 
        0509-022 Cannot load module curl.
        0509-150   Dependent module /usr/lib/libcurl.a(libcurl.so.4) could not be loaded.
        0509-022 Cannot load module .
```

cc/ @sxa555 who is looking at the AIX Ansible stuff.

**Comment by sxa555** [comment]
It should work if LIBPATH is pointing at /usr/lib (although that could well cause other issues of course!) - the libcrypto.a in /opt/freeware/lib doesn't have a non-version-suffixed version of libcrypto.so in it but the one in /usr/lib does. I'm not sure why the one in /opt/freeware/lib doesn't ... You'd expect it to work with the version of curl in there. You could just override it for the execution of curl for now.

**Comment by gibfahn** [comment]
@sxa555 Yep, that works. I'll add the LIBPATH setting to the manual install instructions for now (it's not a problem in CI AFAIK).
