### ISSUE TITLE
Tasks to make ansible/ the default repo

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#712]
List of things we need to do, please put your name against them if you're working on them, and check them off once they're done.

### Tasks:
- [ ] Update the inventory with all of the machines we manage
- [ ] Go through each machine type and confirm that the setup script works on a local machine
  <details><summary>List of Jenkins labels</summary>

  Obtained with `Jenkins.getInstance().getLabels()` in the Script Console:
  - [ ] aix61-ppc64
  - [ ] alpine34-x64
  - [ ] armv7-ubuntu1404
  - [ ] armv7-wheezy
  - [ ] armv8-ubuntu1404
  - [ ] armv8-ubuntu1404-gyp
  - [ ] benchmark
  - [ ] benchmark&&v8test
  - [ ] build-armv6
  - [ ] build-armv7
  - [ ] cc-armv6
  - [ ] cc-armv7
  - [ ] centos5-32
  - [ ] centos5-32-gcc41
  - [ ] centos5-64
  - [ ] centos5-64-gcc41
  - [ ] centos6-64
  - [ ] centos6-64-gcc44
  - [ ] centos7-64
  - [ ] centos7-64-debug
  - [x] debian8-64
  - [ ] debian8-x86
  - [ ] fedora22
  - [ ] fedora23
  - [ ] fedora24
  - [ ] fedora24&&v8test
  - [ ] fedora25-x64
  - [ ] freebsd10-64
  - [ ] freebsd11-x64
  - [ ] iojs-softlayer-benchmark
  - [ ] iojs-voxer-osx1010-1
  - [ ] iojs-voxer-osx1010-2
  - [ ] linter
  - [ ] master
  - [ ] msft-serialport-win1
  - [ ] node-msft-cross-compiler-1
  - [ ] nodejs-scaleway-armv7-wheezy-1
  - [ ] nodejs-scaleway-armv7-wheezy-2
  - [ ] osx1010
  - [ ] pi1-raspbian-wheezy
  - [ ] pi1-raspbian-wheezy-1_of_2
  - [ ] pi1-raspbian-wheezy-1_of_4
  - [ ] pi1-raspbian-wheezy-2_of_2
  - [ ] pi1-raspbian-wheezy-2_of_4
  - [ ] pi1-raspbian-wheezy-3_of_4
  - [ ] pi1-raspbian-wheezy-4_of_4
  - [ ] pi2-raspbian-wheezy
  - [ ] pi2-raspbian-wheezy-1_of_2
  - [ ] pi2-raspbian-wheezy-1_of_4
  - [ ] pi2-raspbian-wheezy-2_of_2
  - [ ] pi2-raspbian-wheezy-2_of_4
  - [ ] pi2-raspbian-wheezy-3_of_4
  - [ ] pi2-raspbian-wheezy-4_of_4
  - [ ] pi3-raspbian-jessie
  - [ ] pi3-raspbian-jessie-1_of_2
  - [ ] pi3-raspbian-jessie-1_of_4
  - [ ] pi3-raspbian-jessie-2_of_2
  - [ ] pi3-raspbian-jessie-2_of_4
  - [ ] pi3-raspbian-jessie-3_of_4
  - [ ] pi3-raspbian-jessie-4_of_4
  - [ ] post-1-release
  - [ ] ppcbe-ubuntu1404
  - [ ] ppcbe-ubuntu1404&&v8test
  - [ ] ppcle-ubuntu1404
  - [ ] ppcle-ubuntu1404&&v8test
  - [ ] rhel72-s390x
  - [ ] rhel72-s390x&&v8test
  - [ ] serialport-win
  - [ ] serialport-win10
  - [ ] smartos14-32
  - [ ] smartos14-64
  - [ ] smartos15-64
  - [ ] smartos16-64
  - [ ] test-azure_msft-win10-x64-1
  - [ ] test-azure_msft-win10-x64-2
  - [ ] test-azure_msft-win10-x64-3
  - [ ] test-azure_msft-win10-x64-4
  - [ ] test-azure_msft-win10-x64-5
  - [ ] test-azure_msft-win2008r2-x64-1
  - [ ] test-azure_msft-win2008r2-x64-2
  - [ ] test-azure_msft-win2008r2-x64-3
  - [ ] test-azure_msft-win2012r2-x64-1
  - [ ] test-azure_msft-win2012r2-x64-2
  - [ ] test-azure_msft-win2012r2-x64-3
  - [ ] test-azure_msft-win2016-x64-1
  - [ ] test-azure_msft-win2016-x64-2
  - [ ] test-azure_msft-win2016-x64-3
  - [ ] test-azure_msft-win2016-x64-4
  - [ ] test-azure_msft-win2016-x64-5
  - [ ] test-azure_msft-win2016-x64-6
  - [ ] test-digitalocean-centos5-x86-1
  - [ ] test-digitalocean-debian8-x64-1
  - [ ] test-digitalocean-fedora22-x64-1
  - [ ] test-digitalocean-fedora23-x64-1
  - [ ] test-digitalocean-fedora24-x64-1
  - [ ] test-digitalocean-fedora25-x64-1
  - [ ] test-digitalocean-fedora25-x64-2
  - [ ] test-digitalocean-freebsd10-x64-1
  - [ ] test-digitalocean-freebsd11-x64-1
  - [ ] test-digitalocean-freebsd11-x64-2
  - [ ] test-digitalocean-ubuntu12-x64-1
  - [ ] test-digitalocean-ubuntu12-x64-2
  - [ ] test-digitalocean-ubuntu14-x64-1
  - [ ] test-digitalocean-ubuntu14-x86-1
  - [ ] test-digitalocean-ubuntu1604-x86-1
  - [ ] test-digitalocean-ubuntu1604_docker-x64-1
  - [ ] test-digitalocean-ubuntu1604_docker_alpine34-x64-1
  - [ ] test-digitalocean-ubuntu1610-x64-1
  - [ ] test-digitalocean-ubuntu1610-x64-2
  - [ ] test-joyent-alpine34-x64-1
  - [ ] test-joyent-alpine34-x64-2
  - [ ] test-joyent-freebsd10-x64-1
  - [ ] test-joyent-freebsd10-x64-2
  - [ ] test-joyent-smartos14-x64-1
  - [ ] test-joyent-smartos14-x64-2
  - [ ] test-joyent-smartos14-x86-1
  - [ ] test-joyent-smartos14-x86-2
  - [ ] test-joyent-smartos15-x64-1
  - [ ] test-joyent-smartos15-x64-2
  - [ ] test-joyent-smartos16-x64-1
  - [ ] test-joyent-smartos16-x64-2
  - [ ] test-linuxonecc-rhel72-s390x-1
  - [ ] test-linuxonecc-rhel72-s390x-2
  - [ ] test-mininodes-ubuntu1604-arm64_odroid_c2-1
  - [ ] test-mininodes-ubuntu1604-arm64_odroid_c2-2
  - [ ] test-mininodes-ubuntu1604-arm64_odroid_c2-3
  - [ ] test-osuosl-aix61-ppc64_be-1
  - [ ] test-osuosl-aix61-ppc64_be-2
  - [ ] test-osuosl-ubuntu14-ppc64_be-1
  - [ ] test-osuosl-ubuntu14-ppc64_be-2
  - [ ] test-osuosl-ubuntu14-ppc64_le-1
  - [ ] test-osuosl-ubuntu14-ppc64_le-2
  - [ ] test-rackspace-centos7-x64-1
  - [ ] test-rackspace-debian8-x64-1
  - [ ] test-rackspace-debian8-x64-2
  - [ ] test-rackspace-fedora22-x64-1
  - [ ] test-rackspace-fedora23-x64-1
  - [ ] test-rackspace-fedora24-x64-1
  - [ ] test-rackspace-freebsd10-x64-1
  - [ ] test-rackspace-ubuntu12-x64-1
  - [ ] test-rackspace-ubuntu1604-x64-1
  - [ ] test-rackspace-ubuntu1604-x64-2
  - [ ] test-rackspace-win2008r2-x64-1
  - [ ] test-rackspace-win2008r2-x64-2
  - [ ] test-rackspace-win2008r2-x64-3
  - [ ] test-rackspace-win2008r2-x64-4
  - [ ] test-rackspace-win2008r2-x64-5
  - [ ] test-rackspace-win2008r2-x64-6
  - [ ] test-rackspace-win2012r2-x64-1
  - [ ] test-rackspace-win2012r2-x64-10
  - [ ] test-rackspace-win2012r2-x64-11
  - [ ] test-rackspace-win2012r2-x64-12
  - [ ] test-rackspace-win2012r2-x64-2
  - [ ] test-rackspace-win2012r2-x64-3
  - [ ] test-rackspace-win2012r2-x64-4
  - [ ] test-rackspace-win2012r2-x64-5
  - [ ] test-rackspace-win2012r2-x64-6
  - [ ] test-rackspace-win2012r2-x64-7
  - [ ] test-rackspace-win2012r2-x64-8
  - [ ] test-rackspace-win2012r2-x64-9
  - [ ] test-requireio-osx1010-x64-1
  - [ ] test-requireio_andineck-debian7-arm_pi1p-1
  - [ ] test-requireio_arm-ubuntu1404-arm64_xgene-1
  - [ ] test-requireio_arm-ubuntu1404-arm64_xgene-2
  - [ ] test-requireio_bengl-debian7-arm_pi1p-2
  - [ ] test-requireio_ceejbot-debian7-arm_pi1p-1
  - [ ] test-requireio_ceejbot-debian7-arm_pi2-1
  - [ ] test-requireio_chrislea-debian7-arm_pi1p-1
  - [ ] test-requireio_continuationlabs-debian7-arm_pi1p-1
  - [ ] test-requireio_davglass-debian7-arm_pi1p-1
  - [ ] test-requireio_davglass-debian8-arm_pi3-1
  - [ ] test-requireio_davglass-ubuntu1404-arm_odroid_xu-1
  - [ ] test-requireio_davglass-ubuntu1404-arm_odroid_xu-2
  - [ ] test-requireio_indieisaconcept-debian7-arm_pi1p-1
  - [ ] test-requireio_jasnell-debian7-arm_pi2-1
  - [ ] test-requireio_joeyvandijk-debian7-arm_pi2-1
  - [ ] test-requireio_joeyvandijk-debian7-arm_pi2-2
  - [ ] test-requireio_kahwee-debian8-arm_pi3-1
  - [ ] test-requireio_louiscntr-debian7-arm_pi2-1
  - [ ] test-requireio_mcollina-debian7-arm_pi2-1
  - [ ] test-requireio_mhdawson-debian7-arm_pi1p-1
  - [ ] test-requireio_mininodes-debian7-arm_pi1p-1
  - [ ] test-requireio_mininodes-debian7-arm_pi2-1
  - [ ] test-requireio_nodesource-ubuntu1404-arm_odroid_xu3-1
  - [ ] test-requireio_notthetup_sayanee-debian8-arm_pi3-1
  - [ ] test-requireio_piccoloaiutante-debian8-arm_pi3-1
  - [ ] test-requireio_pivotalagency-debian8-arm_pi3-1
  - [ ] test-requireio_pivotalagency-debian8-arm_pi3-2
  - [ ] test-requireio_rvagg-debian7-arm_pi2-1
  - [ ] test-requireio_sambthompson-debian7-arm_pi2-1
  - [ ] test-requireio_securogroup-debian7-arm_pi1p-1
  - [ ] test-requireio_securogroup-debian7-arm_pi1p-2
  - [ ] test-requireio_securogroup-debian8-arm_pi3-1
  - [ ] test-requireio_securogroup-debian8-arm_pi3-2
  - [ ] test-requireio_svincent-debian7-arm_pi2-1
  - [ ] test-requireio_svincent-debian7-arm_pi2-2
  - [ ] test-requireio_svincent-debian7-arm_pi2-3
  - [ ] test-requireio_williamkapke-debian8-arm_pi3-1
  - [ ] test-requireio_williamkapke-debian8-arm_pi3-2
  - [ ] test-requireio_williamkapke-debian8-arm_pi3-3
  - [ ] test-softlayer-centos5-x64-1
  - [ ] test-softlayer-centos5-x64-2
  - [ ] test-softlayer-centos6-x64-1
  - [ ] test-softlayer-centos6-x64-2
  - [ ] test-softlayer-centos7-x64-1
  - [ ] test-softlayer-debian8-x86-1
  - [ ] test-softlayer-ubuntu14-x64-1
  - [ ] test-softlayer-ubuntu14-x86-1
  - [ ] ubuntu1204-64
  - [ ] ubuntu1204-clang341-64
  - [ ] ubuntu1404-32
  - [ ] ubuntu1404-64
  - [ ] ubuntu1404-gyp-32
  - [ ] ubuntu1404-gyp-64
  - [ ] ubuntu1604-32
  - [ ] ubuntu1604-64
  - [ ] ubuntu1604-arm64
  - [ ] ubuntu1604_docker
  - [ ] ubuntu1604_docker_alpine34-64
  - [ ] ubuntu1610-x64
  - [ ] v8test
  - [ ] win-vcbt2015
  - [ ] win-vs2013
  - [ ] win-vs2015
  - [ ] win-vs2015-arm
  - [ ] win-vs2015-x86
  - [ ] win10
  - [ ] win10-1p
  - [ ] win10-vs2015
  - [ ] win2008r2
  - [ ] win2008r2-1p
  - [ ] win2008r2-vs2013
  - [ ] win2012r2
  - [ ] win2012r2-1p
  - [ ] win2012r2-vcbt2015
  - [ ] win2012r2-vs2015
  - [ ] win2016
  - [ ] win2016-1p
  - [ ] win2016-vs2015]

  </details>
- [ ] Do the same with a temp machine from each provider actually connecting to Jenkins

**Please add your own**

**Comment by santigimeno** [comment]
I've tested the scripts on a `freebsd11-x64` box and it looks they work fine (I've only tested that the ansible scripts run without problems not that the box ends in the expected state)

**Comment by maclover7** [comment]
Moving this to #1277
